# Generated by Django 5.2.1 on 2025-06-03 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_remove_order_item_orderitem_order_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='description',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
